### ISSUE TITLE
Configure folder (or use Obsidian default) for storing snaps and videos

### ISSUE THREAD

**Issue by agnoldo** [aldrinjenson/obsidian-camera#10]
Hello! First of all, congratulations for the great idea and plugin. This is a very interesting initiative, very useful. In my tests, the plugin worked well both in my smartphone (Samsung Galaxy S21) and in my computer (Dell Latitude running Windows 10).

The only minor problem I had with the plugin is the fact that it saves the snap in a fixed folder (/attachments/snap) and, since my vault is in Portuguese, my attachment folder has another name. Is it possible to use the default attachment folder from Obsidian? Or even configure one for the plugin?

Thanks for your work!

**Comment by aldrinjenson** [comment]
![image](https://user-images.githubusercontent.com/53407417/185206478-a7645ee9-2307-461d-af81-931ff275ea82.png)

Fixed in version [1.3.0](https://github.com/aldrinjenson/obsidian-camera/releases/tag/1.3.0)
Have added a new settings option for entering custom Folder path.
The plugin will create the directory if not already existing.

**Comment by agnoldo** [comment]
Thank you very much, @aldrinjenson ! I already tested here and I can confirm it is working great.

**Comment by zeltak** [comment]
thx! was wondering of the folder could be relative to the file you are working in? so that it always saves in a subfolder `assets` in the same folder the file you are working on is. Ie being able to define something like `./assets` in the folder locations?

thx!

Z
