### ISSUE TITLE
Issues with image (not video)

### ISSUE THREAD

**Issue by merlinuwe** [aldrinjenson/obsidian-camera#12]
Hi again ;-)

When I add an image, I always get a black image with the text "please start iriun webcam". This image is saved and shown in the note.

![image_Dec_17_2022_20-48-50_GMT](https://user-images.githubusercontent.com/4138869/208264655-2bdf67d3-fa11-4e56-a79a-774059496e1c.png)

(Video works.)

I use a Lenovo Thinkpad Yoga X13 with Windows 10 and latest obsidian with latest plugins:

![OnPaste 20221217-211508](https://user-images.githubusercontent.com/4138869/208264602-c72f19c9-b39a-4510-91c4-d28c082334bf.png)

The cross x to close the window does not work.

If I press the button "switch camera", the light at the right of my camera goes on. But I cannot switch it off by clicking on the same button. It makes no difference, if I switch the button or not.

I also reinstalled the plugin.

Can you help me, please?

**Comment by aldrinjenson** [comment]
Hi,
Can't replicate this issue.
I think this may be due to some other installed plugin conflicting. 

Can you try creating a new folder in your plugins directory and moving all other plugin folders except obsidian-camera to this new folder temporarily. This should have the same effect as uninstalling all other plugins temporarily. Then restart obsidian and see if the issue persists. 

You can move the folder back afterwards to achieve the previous state.

Let me know how it goes.
